title:              OFFFBRAND

# Versioning
current_version: 1.5.0
foundation_version: 6.0.0

author:
  name:             Michael Fan
  email:            user@domain.com

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
baseurl:            ""
url:                http://offfbrand.com

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS

name:               OFFFBRAND
description :       OFFFBRAND Clothing Shop
copyright:          Copyright (c) 2016



# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed
